EmployeeProfile/Models/EmployeeDetail.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeProfile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeDetail()
        {
            this.AsignClienttoEmps = new HashSet<AsignClienttoEmp>();
            this.Bills = new HashSet<Bill>();
            this.ClientMasters = new HashSet<ClientMaster>();
        }
    
        public int EID { get; set; }
        public int EmpId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public Nullable<long> Phoneno { get; set; }
        public string Worklocation { get; set; }
        public Nullable<int> Employee_Designation_FK { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> SubDepartmentId { get; set; }
        public string LancesoftID { get; set; }
        public Nullable<int> EmployeeTypeId { get; set; }
        public Nullable<int> ReportingManagerId { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public Nullable<int> Pincode { get; set; }
        public Nullable<bool> Active_Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string Vertical { get; set; }
        public string Gender { get; set; }
        public string Address_status { get; set; }
        public Nullable<bool> Working_internal { get; set; }
        public Nullable<System.DateTime> Joiningdate { get; set; }
        public Nullable<System.DateTime> Dateofbirth { get; set; }
        public Nullable<decimal> Salary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignClienttoEmp> AsignClienttoEmps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientMaster> ClientMasters { get; set; }
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual Employee_Type Employee_Type { get; set; }
        public virtual Login Login { get; set; }
        public virtual SubDepartment SubDepartment { get; set; }
        public decimal lead_p_l { get; set; }
        public decimal Leadprofit { get; set; }
        public decimal Managerprofit_Loss { get; set; }
        public decimal GMprofit_Loss { get; set; }
        public decimal CHprofit_Loss { get; set; }
    }
}

EmployeeProfile/Controllers/EmployeeDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EmployeeProfile.Models;



namespace EmployeeProfile.Controllers
{
    [Authorize]
    public class EmployeeDetailsController : Controller
    {
        private Employee_PortalEntities db = new Employee_PortalEntities();



        // GET: EmployeeDetails



        public ActionResult Index()
        {
            var employeeDetails = db.EmployeeDetails.Include(e => e.Department).Include(e => e.Designation).Include(e => e.Employee_Type).Include(e => e.Login).Include(e => e.SubDepartment);
            return View(employeeDetails.ToList());
        }



        // GET: EmployeeDetails/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EmployeeDetail employeeDetail = db.EmployeeDetails.Find(id);
            if (employeeDetail == null)
            {
                return HttpNotFound();
            }
            return View(employeeDetail);
        }



        // GET: EmployeeDetails/Create
        public ActionResult Create()
        {
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "DepartmentName");
            ViewBag.Employee_Designation_FK = new SelectList(db.Designations, "DesignationId", "DesignationName");
            ViewBag.EmployeeTypeId = new SelectList(db.Employee_Type, "EmployeeTypeid", "EmployeeType");
            ViewBag.ReportingManagerId = new SelectList(db.Logins.Where(x => x.Designation != "CONSULTANT"), "ID", "Name");
            ViewBag.SubDepartmentId = new SelectList(db.SubDepartments, "SDepartmentId", "Name");
            return View();
        }



        // POST: EmployeeDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EID,EmpId,Firstname,Lastname,Email,Phoneno,Worklocation,Employee_Designation_FK,DepartmentId,SubDepartmentId,LancesoftID,EmployeeTypeId,ReportingManagerId,Country,State,City,Street,Pincode,Active_Status,CreatedDate,CreatedBy,Vertical,Gender,Address_status,Working_internal,Joiningdate,Dateofbirth,Salary")] EmployeeDetail employeeDetail)
        {
            if (ModelState.IsValid)
            {
                Login lg = new Login();
                lg.Active_Status = 1;
                lg.CreateBy = employeeDetail.CreatedBy;
                var dd = db.Designations.Where(x => x.DesignationId == employeeDetail.Employee_Designation_FK).FirstOrDefault();

                lg.Designation = dd.DesignationName;
                lg.Email = employeeDetail.Email;
                lg.Mobileno = employeeDetail.Phoneno;
                lg.Name = employeeDetail.Firstname;// + " " + employeeDetail.Lastname;
                lg.Password = employeeDetail.Firstname;
                lg.UserName = employeeDetail.Lastname;
                lg.Empid = employeeDetail.EmpId;
                db.Logins.Add(lg);
                db.SaveChanges();
                employeeDetail.EmpId = lg.ID;



                db.EmployeeDetails.Add(employeeDetail);
                db.SaveChanges();
                return RedirectToAction("Index");
            }



            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "DepartmentName", employeeDetail.DepartmentId);
            ViewBag.Employee_Designation_FK = new SelectList(db.Designations, "DesignationId", "DesignationName", employeeDetail.Employee_Designation_FK);
            ViewBag.EmployeeTypeId = new SelectList(db.Employee_Type, "EmployeeTypeid", "EmployeeType", employeeDetail.EmployeeTypeId);
            ViewBag.ReportingManagerId = new SelectList(db.Logins, "ID", "Name", employeeDetail.ReportingManagerId);
            ViewBag.SubDepartmentId = new SelectList(db.SubDepartments, "SDepartmentId", "Name", employeeDetail.SubDepartmentId);
            return View(employeeDetail);
        }



        // GET: EmployeeDetails/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EmployeeDetail employeeDetail = db.EmployeeDetails.Find(id);
            if (employeeDetail == null)
            {
                return HttpNotFound();
            }
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "DepartmentName", employeeDetail.DepartmentId);
            ViewBag.Employee_Designation_FK = new SelectList(db.Designations, "DesignationId", "DesignationName", employeeDetail.Employee_Designation_FK);
            ViewBag.EmployeeTypeId = new SelectList(db.Employee_Type, "EmployeeTypeid", "EmployeeType", employeeDetail.EmployeeTypeId);
            ViewBag.ReportingManagerId = new SelectList(db.Logins, "ID", "Name", employeeDetail.ReportingManagerId);
            ViewBag.SubDepartmentId = new SelectList(db.SubDepartments, "SDepartmentId", "Name", employeeDetail.SubDepartmentId);
            return View(employeeDetail);
        }



        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EmployeeDetail employeeDetail)
        {
            if (ModelState.IsValid)
            {
                db.Entry(employeeDetail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "DepartmentName", employeeDetail.DepartmentId);
            ViewBag.Employee_Designation_FK = new SelectList(db.Designations, "DesignationId", "DesignationName", employeeDetail.Employee_Designation_FK);
            ViewBag.EmployeeTypeId = new SelectList(db.Employee_Type, "EmployeeTypeid", "EmployeeType", employeeDetail.EmployeeTypeId);
            ViewBag.ReportingManagerId = new SelectList(db.Logins, "ID", "Name", employeeDetail.ReportingManagerId);
            ViewBag.SubDepartmentId = new SelectList(db.SubDepartments, "SDepartmentId", "Name", employeeDetail.SubDepartmentId);
            return View(employeeDetail);
        }



        // GET: EmployeeDetails/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EmployeeDetail employeeDetail = db.EmployeeDetails.Find(id);
            if (employeeDetail == null)
            {
                return HttpNotFound();
            }
            return View(employeeDetail);
        }



        // POST: EmployeeDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EmployeeDetail employeeDetail = db.EmployeeDetails.Find(id);
            db.EmployeeDetails.Remove(employeeDetail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EmployeeProfile/Views/EmployeeDetails/Delete.cshtml
@model EmployeeProfile.Models.EmployeeDetail

@{
    ViewBag.Title = "Delete";
}

<h2>Delete EmployeeDetail</h2>

<style>

    /* table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        background-color: #EBEBEB;
    }*/

    dt, dd {
        /* background-color: #8d2929;*/
        color: #333;
    }

    /*td, th {
        border: 1px solid #99b3ff;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #F5F6FA;
    }*/

    body {
        background-color: #99bbff;
    }
</style>
<div>
    
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EmpId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmpId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lastname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lastname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phoneno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phoneno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Worklocation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Worklocation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LancesoftID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LancesoftID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pincode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pincode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active_Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active_Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vertical)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vertical)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address_status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address_status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Working_internal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Working_internal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Joiningdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Joiningdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dateofbirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dateofbirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department.DepartmentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.DepartmentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Designation.DesignationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Designation.DesignationName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee_Type.EmployeeType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee_Type.EmployeeType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Login.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Login.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubDepartment.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubDepartment.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    @*<input type="submit" value="Delete" class="btn btn-danger" /> |*@
    <input type="button" class="btn btn-danger" value="Delete" onclick="location.href='@Url.Action("Delete", "EmployeeDetails", new { id = Model.EmpId })'" />
    <input type="button" class="btn btn-primary" value="Back to List" onclick="location.href='@Url.Action("Index", "EmployeeDetails", new { id = Model.EmpId })'" />
    @*@Html.ActionLink("Back to List", "Index")*@
</div>
    }
</div>

EmployeeProfile/Views/EmployeeDetails/Details.cshtml
@model EmployeeProfile.Models.EmployeeDetail

@{
    ViewBag.Title = "Details";
}

<h2>EmployeeDetail</h2>
<style>

    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        background-color: #EBEBEB;
    }

    dt {
        /* background-color: #8d2929;*/
        color: #333;
    }

    dd {
        color: white;
    }

    /*td, th {
        border: 1px solid #99b3ff;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #F5F6FA;
    }*/

    body {
        background-color: #99bbff;
    }
</style>

<div>
 
 
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EmpId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmpId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lastname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lastname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phoneno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phoneno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Worklocation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Worklocation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LancesoftID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LancesoftID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pincode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pincode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active_Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active_Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vertical)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vertical)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address_status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address_status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Working_internal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Working_internal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Joiningdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Joiningdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dateofbirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dateofbirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department.DepartmentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.DepartmentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Designation.DesignationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Designation.DesignationName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee_Type.EmployeeType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee_Type.EmployeeType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Login.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Login.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubDepartment.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubDepartment.Name)
        </dd>

    </dl>
</div>
<p>

    <input type="button" class="btn btn-primary" value="Edit" onclick="location.href='@Url.Action("Edit", "EmployeeDetails", new { id = Model.EID })'" />
    <input type="button" class="btn btn-primary" value="Back to List" onclick="location.href='@Url.Action("Index", "EmployeeDetails", new { id = Model.EID })'" />


    @*@Html.ActionLink("Edit", "Edit", new { id = Model.EID }) |
    @Html.ActionLink("Back to List", "Index")*@
</p>

EmployeeProfile/Views/EmployeeDetails/Index.cshtml
@model IEnumerable<EmployeeProfile.Models.EmployeeDetail>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        background-color: #EBEBEB;
    }

    th {
        background-color: #152D53;
        color: white;
    }

    td, th {
        border: 1px solid #99b3ff;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #F5F6FA;
    }

    body 
    {
        background-color: #FFFFFF;
    }
    


</style>





<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EmpId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Firstname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lastname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phoneno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Worklocation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LancesoftID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Street)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pincode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Active_Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Vertical)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address_status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Working_internal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Joiningdate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dateofbirth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salary)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Department.DepartmentName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Designation.DesignationName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Employee_Type.EmployeeType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Login.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubDepartment.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.EmpId)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Firstname)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Lastname)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Email)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Phoneno)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Worklocation)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.LancesoftID)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Country)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.State)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.City)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Street)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Pincode)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Active_Status)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CreatedDate)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CreatedBy)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Vertical)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Gender)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Address_status)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Working_internal)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Joiningdate)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Dateofbirth)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Salary)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Department.DepartmentName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Designation.DesignationName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Employee_Type.EmployeeType)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Login.Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.SubDepartment.Name)
    </td>

    <td>
        @if (User.IsInRole("HR"))
        {
            <input type="button" class="btn btn-primary" value="Edit" onclick="location.href='@Url.Action("Edit", "EmployeeDetails", new { id = item.EID })'" />

            @*<input type="button" class="btn btn-danger" value="Delete" onclick="location.href='@Url.Action("Delete", "EmployeeDetails", new { id = item.EmpId })'" />*@
       }


        <input type="button" class="btn btn-info" value="Details" onclick="location.href='@Url.Action("Details", "EmployeeDetails", new { id = item.EID })'" />
    </td>

    
</tr>
}

</table>