EmployeeProfile/Controllers/MDController.cs
using EmployeeProfile.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeProfile.Controllers
{
    [Authorize]
    public class MDController : Controller
    {
        // GET: md
        public Employee_PortalEntities db = new Employee_PortalEntities();
        public ActionResult Index()

        {

            var user = TempData["UserId"] as Login;

            var employeeDetails = db.EmployeeDetails.Where(x => x.EmpId == user.ID).FirstOrDefault();

            var data = db.EmployeeDetails.Where(x => x.ReportingManagerId == user.ID).ToList();

            decimal CH_p_l = 0;
            int MDtenure = 0;
            decimal MDprofit = 0;
            decimal MD_p_l = 0;

            AddCalculationDetails obj1 = new AddCalculationDetails();
            GetAllEployeedetails model = new GetAllEployeedetails();

            foreach (var item in data)
            {

                CH_p_l += CHCalculation(item.EmpId);

                item.CHprofit_Loss = CHCalculation(item.EmpId);
            }

            if (user.ID == employeeDetails.EmpId)
            {

                DateTime jd1 = DateTime.Parse(employeeDetails.Joiningdate.Value.ToString());

                MDtenure = (DateTime.Parse(DateTime.Now.ToString()) - jd1).Days / 30;
                MDprofit = MDtenure * employeeDetails.Salary.Value;
                MD_p_l = CH_p_l - MDprofit;
            }
            //foreach (var item in data)
            //{

            //    item.CHprofit = CHprofit;
            //}
            ViewBag.MDprofit = MD_p_l;


            return View(data);




        }
        public decimal CHCalculation(int id)
        {
            var employeeDetails = db.EmployeeDetails.Where(x => x.EmpId == id).FirstOrDefault();
            var data = db.EmployeeDetails.Where(x => x.ReportingManagerId == id).ToList();
            int CHtenure = 0;
            decimal CHprofit = 0;
            decimal CH_p_l = 0;
            decimal GM_p_l = 0;

            AddCalculationDetails obj1 = new AddCalculationDetails();
            if (employeeDetails.EmpId == id)
            {
                foreach (var item in data)
                {

                    GM_p_l += GMcalculation(item.EmpId);


                }

            }
            if (employeeDetails.EmpId == id)
            {

                DateTime jd1 = DateTime.Parse(employeeDetails.Joiningdate.Value.ToString());

                CHtenure = (DateTime.Parse(DateTime.Now.ToString()) - jd1).Days / 30;
                CHprofit = CHtenure * employeeDetails.Salary.Value;
                CH_p_l = GM_p_l - CHprofit;

            }
            return CH_p_l;

        }
        public decimal GMcalculation(int id)
        {
            var employeeDetails = db.EmployeeDetails.Where(x => x.EmpId == id).FirstOrDefault();
            var data = db.EmployeeDetails.Where(x => x.ReportingManagerId == id).ToList();
            int GMtenure = 0;
            decimal GMprofit = 0;
            decimal GM_p_l = 0;
            decimal Manager_p_l = 0;

            AddCalculationDetails obj1 = new AddCalculationDetails();
            if (employeeDetails.EmpId == id)
            {
                foreach (var item in data)
                {

                    Manager_p_l += Managercalculation(item.EmpId);


                }

            }
            if (employeeDetails.EmpId == id)
            {

                DateTime jd1 = DateTime.Parse(employeeDetails.Joiningdate.Value.ToString());

                GMtenure = (DateTime.Parse(DateTime.Now.ToString()) - jd1).Days / 30;
                GMprofit = GMtenure * employeeDetails.Salary.Value;
                GM_p_l = Manager_p_l - GMprofit;

            }
            return GM_p_l;

        }
        public decimal Managercalculation(int id)
        {
            var employeeDetails = db.EmployeeDetails.Where(x => x.EmpId == id).FirstOrDefault();
            var data = db.EmployeeDetails.Where(x => x.ReportingManagerId == id).ToList();
            int Managertenure = 0;
            decimal Managerprofit = 0;
            decimal Manager_p_l = 0;
            decimal lead_p_l = 0;

            AddCalculationDetails obj1 = new AddCalculationDetails();
            if (employeeDetails.EmpId == id)
            {
                foreach (var item in data)
                {

                    lead_p_l += leadCalculation(item.EmpId);


                }

            }
            if (employeeDetails.EmpId == id)
            {

                DateTime jd1 = DateTime.Parse(employeeDetails.Joiningdate.Value.ToString());

                Managertenure = (DateTime.Parse(DateTime.Now.ToString()) - jd1).Days / 30;
                Managerprofit = Managertenure * employeeDetails.Salary.Value;
                Manager_p_l = lead_p_l - Managerprofit;

            }

            return Manager_p_l;


        }
        public decimal leadCalculation(int id)
        {
            var employeeDetails = db.EmployeeDetails.Where(x => x.EmpId == id).FirstOrDefault();
            var data = db.EmployeeDetails.Where(x => x.ReportingManagerId == id).ToList();
            int leadtenure = 0;
            decimal leadprofit = 0;
            decimal lead_p_l = 0;
            decimal profitdata = 0;

            AddCalculationDetails obj1 = new AddCalculationDetails();
            if (employeeDetails.EmpId == id)
            {

                DateTime jd1 = DateTime.Parse(employeeDetails.Joiningdate.Value.ToString());

                leadtenure = (DateTime.Parse(DateTime.Now.ToString()) - jd1).Days / 30;
                leadprofit = leadtenure * employeeDetails.Salary.Value;


            }
            if (employeeDetails.EmpId == id)
            {
                foreach (var item in data)
                {
                    profitdata += Calculation(item.EID);
                    lead_p_l = profitdata - leadprofit;

                }
            }
            return lead_p_l;


        }
        public decimal Calculation(int Id)
        {
            AsignClienttoEmp obj1 = new AsignClienttoEmp();
            GetAllEployeedetails model = new GetAllEployeedetails();
            List<AsignClienttoEmp> lObj = new List<AsignClienttoEmp>();
            List<Bill> lObj1 = new List<Bill>();
            model.eployeeDetails = db.EmployeeDetails.Where(x => x.EID == Id).FirstOrDefault();
            var clientDetails = db.AsignClienttoEmps.Where(x => x.EID == Id).ToList();
            lObj = clientDetails;
            var billDetails = db.Bills.Where(x => x.EID == Id).ToList();
            lObj1 = billDetails;
            model.clientDetails = lObj;


            List<AddCalculationDetails> obj = new List<AddCalculationDetails>();
            var Bill_details = db.Bills.Where(x => x.EID == Id).FirstOrDefault();
            var employeeDetails = db.EmployeeDetails.Where(x => x.EID == Id).FirstOrDefault();
            var AsignClienttoEmp = db.AsignClienttoEmps.Where(x => x.EID == Id).FirstOrDefault();

            if (clientDetails != null && clientDetails.Count() > 0)
            {
                int btenure = 0;
                int tenure = 0;
                int Ctenure = 0;
                int TotalCtenure = 0;
                decimal paidtillnow = 0;
                decimal ClientBilling = 0;
                decimal Profit_loss = 0;
                foreach (var item in clientDetails)
                {

                    DateTime JD = DateTime.Parse(employeeDetails.Joiningdate.Value.ToString());

                    tenure = (DateTime.Parse(DateTime.Now.ToString()) - JD).Days / 30;
                    paidtillnow = (Convert.ToDecimal(employeeDetails.Salary) * tenure);
                    DateTime p1 = (clientDetails != null ? item.POS.Value : DateTime.Now);
                    DateTime p2 = (clientDetails != null ? item.POE.Value : DateTime.Now);
                    //int Ctenure = ((p2.Year - p1.Year) * 12) + p2.Month - p1.Month;

                    if (employeeDetails.EID == AsignClienttoEmp.EID)
                    {
                        Ctenure = ((p2.Year - p1.Year) * 12) + p2.Month - p1.Month;
                        TotalCtenure = TotalCtenure + Ctenure;

                    }
                    ClientBilling = Convert.ToDecimal(item.ClientBilling);

                }
                btenure = tenure - TotalCtenure;

                decimal bench_exp = Convert.ToDecimal(employeeDetails.Salary);
                decimal bench_expenes = 0;

                if (Bill_details != null)
                {
                    bench_expenes = btenure * (Bill_details.FoodCost.Value + Bill_details.TransportationCost.Value + Bill_details.CubicleCost.Value);
                }
                decimal Clientsal = TotalCtenure * (clientDetails != null ? Convert.ToDecimal(ClientBilling) : 0);
                if (employeeDetails.Salary != null && employeeDetails.Salary > 0 && tenure > 0)
                {
                    decimal Total = paidtillnow;
                }

                Profit_loss = Clientsal - (paidtillnow + bench_expenes);

                return Profit_loss;
            }
            else
            {
                int btenure = 0;
                int tenure = 0;

                DateTime JD = DateTime.Parse(employeeDetails.Joiningdate.Value.ToString());

                tenure = (DateTime.Parse(DateTime.Now.ToString()) - JD).Days / 30;
                decimal paidtillnow = (Convert.ToDecimal(employeeDetails.Salary) * tenure);

                int TotalCtenure = 0;
                btenure = tenure - TotalCtenure;

                decimal bench_exp = Convert.ToDecimal(employeeDetails.Salary);
                decimal bench_expenes = 0;


                if (Bill_details != null)
                {
                    bench_expenes = btenure * (Bill_details.FoodCost.Value + Bill_details.TransportationCost.Value + Bill_details.CubicleCost.Value);
                }

EmployeeProfile/Views/MD/CHDetails.cshtml
@model IEnumerable<EmployeeProfile.Models.EmployeeDetail>

@{
    ViewBag.Title = "Index";
}

<h2><br />
   
</h2>

<p>

</p>
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        background-color: #EBEBEB;
    }

    th {
        background-color: #152D53;
        color: white;
    }

    td, th {
        border: 1px solid #99b3ff;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #F5F6FA;
    }

    body {
        background-color: #FFFFFF;
    }
    </style>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Firstname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lastname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phoneno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Worklocation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LancesoftID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Street)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pincode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Active_Status)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Vertical)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address_status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Working_internal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Joiningdate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dateofbirth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salary)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Department.DepartmentName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Designation.DesignationName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Employee_Type.EmployeeType)
        </th>
        <th>
            <label>Reporting Person</label>
        </th>
        <th>
            <label>Sub-Department</label>
        </th>
        <th>
            <label>GMprofit_loss</label>
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Firstname)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Lastname)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Email)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Phoneno)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Worklocation)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.LancesoftID)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Country)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.State)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.City)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Street)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Pincode)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Active_Status)
    </td>
    @*<td>
            @Html.DisplayFor(modelItem => item.CreatedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedBy)
        </td>*@
    <td>
        @Html.DisplayFor(modelItem => item.Vertical)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Gender)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Address_status)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Working_internal)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Joiningdate)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Dateofbirth)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Salary)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Department.DepartmentName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Designation.DesignationName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Employee_Type.EmployeeType)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Login.Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.SubDepartment.Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.GMprofit_Loss)
    </td>
    <td>

        <input type="button" class="btn btn-primary" value="View" onclick="location.href='@Url.Action("GMDetails", "MD", new { id = item.EmpId })'" />


    </td>


</tr>
    }

</table>

EmployeeProfile/Views/MD/Index.cshtml
@model IEnumerable<EmployeeProfile.Models.EmployeeDetail>

@{
    ViewBag.Title = "Index";
}

<h1>
    <br />
</h1>

<p>
    <label>MDProfit/Loss</label>
    @ViewBag.MDprofit
</p>
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        background-color: #EBEBEB;
    }

    th {
        background-color: #152D53;
        color: white;
    }

    td, th {
        border: 1px solid #99b3ff;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #F5F6FA;
    }

    body {
        background-color: #FFFFFF;
    }
</style>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Firstname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lastname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phoneno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Worklocation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LancesoftID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Street)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pincode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Active_Status)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Vertical)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address_status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Working_internal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Joiningdate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dateofbirth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salary)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Department.DepartmentName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Designation.DesignationName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Employee_Type.EmployeeType)
        </th>
        <th>

            <label>Reporting Person</label>
        </th>
        <th>

            <label>Sub-Department</label>
        </th>
        <th>

            <label>CHprofit_loss</label>
        </th>


        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Firstname)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Lastname)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Email)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Phoneno)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Worklocation)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.LancesoftID)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Country)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.State)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.City)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Street)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Pincode)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Active_Status)

    <td>
        @Html.DisplayFor(modelItem => item.Vertical)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Gender)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Address_status)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Working_internal)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Joiningdate)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Dateofbirth)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Salary)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Department.DepartmentName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Designation.DesignationName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Employee_Type.EmployeeType)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Login.Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.SubDepartment.Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CHprofit_Loss)
    </td>


    <td>

        @*@Html.ActionLink("View", "CHDetails", new { id = item.EmpId })*@
        <input type="button" class="btn btn-primary" value="View" onclick="location.href='@Url.Action("CHDetails", "MD", new { id = item.EmpId })'" />

    </td>

</tr>
    }

</table>

EmployeeProfile/Views/MD/LeadDetails.cshtml
@model IEnumerable<EmployeeProfile.Models.EmployeeDetail>

@{
    ViewBag.Title = "Index";
}

<h2><br />
    
    </h2>

<p>

</p>
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        background-color: #EBEBEB;
    }

    th {
        background-color: #152D53;
        color: white;
    }

    td, th {
        border: 1px solid #99b3ff;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #F5F6FA;
    }

    body {
        background-color: #FFFFFF;
    }
</style>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Firstname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lastname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phoneno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Worklocation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LancesoftID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Street)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pincode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Active_Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Vertical)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address_status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Working_internal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Joiningdate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dateofbirth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salary)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Department.DepartmentName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Designation.DesignationName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Employee_Type.EmployeeType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Login.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubDepartment.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Firstname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lastname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phoneno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Worklocation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LancesoftID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Street)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pincode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Active_Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vertical)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address_status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Working_internal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Joiningdate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dateofbirth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Department.DepartmentName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Designation.DesignationName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Employee_Type.EmployeeType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Login.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SubDepartment.Name)
            </td>
            <td>

                <input type="button" class="btn btn-primary" value="View" onclick="location.href='@Url.Action("Details", "MD", new { id = item.EID })'" />


            </td>


        </tr>
    }

</table>