EmployeeProfile/Models/ClientMaster.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeProfile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientMaster
    {
        public int ClientId { get; set; }
        public string ClientName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> EID { get; set; }
    
        public virtual EmployeeDetail EmployeeDetail { get; set; }
    }
}

EmployeeProfile/Controllers/ClientMastersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EmployeeProfile.Models;

namespace EmployeeProfile.Controllers
{
    [Authorize]
    public class ClientMastersController : Controller
    {
        private Employee_PortalEntities db = new Employee_PortalEntities();

        // GET: ClientMasters
        public ActionResult Index()
        {
            return View(db.ClientMasters.ToList());
        }

        // GET: ClientMasters/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClientMaster clientMaster = db.ClientMasters.Find(id);
            if (clientMaster == null)
            {
                return HttpNotFound();
            }
            return View(clientMaster);
        }

        // GET: ClientMasters/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ClientMasters/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ClientId,ClientName,CreatedDate,CreatedBy")] ClientMaster clientMaster)
        {
            if (ModelState.IsValid)
            {
                db.ClientMasters.Add(clientMaster);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(clientMaster);
        }

        // GET: ClientMasters/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClientMaster clientMaster = db.ClientMasters.Find(id);
            if (clientMaster == null)
            {
                return HttpNotFound();
            }
            return View(clientMaster);
        }

        // POST: ClientMasters/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ClientId,ClientName,CreatedDate,CreatedBy")] ClientMaster clientMaster)
        {
            if (ModelState.IsValid)
            {
                db.Entry(clientMaster).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(clientMaster);
        }

        // GET: ClientMasters/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClientMaster clientMaster = db.ClientMasters.Find(id);
            if (clientMaster == null)
            {
                return HttpNotFound();
            }
            return View(clientMaster);
        }

        // POST: ClientMasters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ClientMaster clientMaster = db.ClientMasters.Find(id);
            db.ClientMasters.Remove(clientMaster);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EmployeeProfile/Views/ClientMasters/Create.cshtml
@model EmployeeProfile.Models.ClientMaster

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
<style>

    /* table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        background-color: #EBEBEB;
    }*/

    div {
        /* background-color: #8d2929;*/
        color: #333;
    }

    /*td, th {
        border: 1px solid #99b3ff;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #F5F6FA;
    }*/

    body {
        background-color: #99bbff;
    }
</style>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ClientName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClientName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClientName, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

EmployeeProfile/Views/ClientMasters/Delete.cshtml
@model EmployeeProfile.Models.ClientMaster

@{
    ViewBag.Title = "Delete";
}

<h2>Delete ClientMaster detailes</h2>


<div>
 
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClientName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EmployeeProfile/Views/ClientMasters/Details.cshtml
@model EmployeeProfile.Models.ClientMaster

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ClientMaster</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClientName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ClientId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EmployeeProfile/Views/ClientMasters/Edit.cshtml
@model EmployeeProfile.Models.ClientMaster

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ClientMaster</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ClientId)

        <div class="form-group">
            @Html.LabelFor(model => model.ClientName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClientName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClientName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

EmployeeProfile/Views/ClientMasters/Index.cshtml
@model IEnumerable<EmployeeProfile.Models.ClientMaster>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        background-color: #EBEBEB;
    }

    th {
        background-color: #152D53;
        color: white;
    }

    td, th {
        border: 1px solid #99b3ff;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #F5F6FA;
    }

    body {
        background-color: #FFFFFF;
    }
</style>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ClientName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.ClientName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CreatedDate)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CreatedBy)
    </td>
    @*<td>
        @Html.ActionLink("Edit", "Edit", new { id = item.ClientId }) |
        @Html.ActionLink("Details", "Details", new { id = item.ClientId }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.ClientId })
    </td>*@

    <td>

        <input type="button" class="btn btn-primary" value="Edit" onclick="location.href='@Url.Action("Edit", "ClientMasters", new { id = item.ClientId })'" />

        <input type="button" class="btn btn-danger" value="Delete" onclick="location.href='@Url.Action("Delete", "ClientMasters", new { id = item.ClientId })'" />

        <input type="button" class="btn btn-info" value="Details" onclick="location.href='@Url.Action("Details", "ClientMasters", new { id = item.ClientId })'" />
    </td>
</tr>
}

</table>